### PR TITLE
project completion requirement fully meet

### PR DESCRIPTION
**Pull request by em-em-D**
Milestone5 project requirement fully meet and all functions fully functional

### CODE REVIEW

**Review by suretrust — CHANGES_REQUESTED** [review]
Hi @em-em-D, 👋 

### Great job thus far! 🙌 Just a few bugs. 👇 `

- [ ] The `+/-` is working as `%`, let's fix this.

- [ ] When I click `.` directly instead of working similar to pressing `0.`, it gives an error. You can either catch this error or just ensure pressing `.` works similarly to pressing `0.`.

- [ ] Finally, please format your `readME` properly. Use headers to make it more readable.

**KIndly submit another CRR once these issues have been solved.** _Happy coding!_ 🎉

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Changes required :muscle: 
Hi @em-em-D :hand: 
Nice job so far on this milestone :clap: 
But we need to work on some changes before moving on.

- [ ] We need to change the linter.yml file to one from the [React and Redux module](https://github.com/microverseinc/linters-config/blob/master/react-redux/.github/workflows/linters.yml). Right now you projects use the linter.yml configured for the Javascript module.

- [ ] In the given design, the button 0 takes 50% of the row space. We need to try to match that style, and we also need to remove the blank empty space.
**Given design**
Screenshot from 2020-09-17 16-49-00
**Your design**
Screenshot from 2020-09-17 16-48-13

Please kindly submit for code review again after implementing the requested changes.
Feel free to message me on slack if you have any questions :smile: 
Happy Coding :computer: 
**Sergio Torres**

**Comment by em-em-D** [comment]
Hi Sergio Torres,

Thanks for the code review, quick observations with your request.
(1) my Ui design must not look like everyone owns to start with, so I wouldn't be changing my 0 button design to take 50%.
(2) secondly, the Linter.yml file was provided by microverse for this project I got that from the project set up, if it ever was an issue I believe other  TSE would have mention form milestone 1. so please kindly review again and approve my work or I would lodge a formal complaint to student success. thanks again for your time

**Comment by Torres-ssf** [comment]
> Hi Sergio Torres,
> 
> Thanks for the code review, quick observations with your request.
> (1) my Ui design must not look like everyone owns to start with, so I wouldn't be changing my 0 button design to take 50%.
> (2) secondly, the Linter.yml file was provided by microverse for this project I got that from the project set up, if it ever was an issue I believe other TSE would have mention form milestone 1. so please kindly review again and approve my work or I would lodge a formal complaint to student success. thanks again for your time

I'm really sorry about this whole situation @em-em-D. It seems those changes were not requested in the first review so I should have requested then as **optional**. Please kindly submit for code review again and in the next review the PR will be approved since all requirements from the first review were fulfilled. Sorry for your troubles again.

**Comment by em-em-D** [comment]
@segiotorres Thank you for acknowledging, your open minded gesture is
appreciated

**Review by shloch — APPROVED** [review]
## Hello @em-em-D 

On the basis of the conversation from former TSEs..this is approved

Great job and happy coding on next projects

**Pull request merged**
